"use strict";
exports.__esModule = true;
var kuznec_1 = require("./kuznec");
var kuz = new kuznec_1.Kuznec();
console.log(kuz.L([1]));
// let pol1 = new Polynom(0, [1, 3, 0, 1]);
// let pol2 = new Polynom(0, [1, 1]);
// console.log(pol1.Mult(pol2));
// console.log("pol1 = " ,pol1);
// console.log("pol2 = " ,pol2);
// console.log(pol1.Mod(pol2));
// console.log("pol1 = " ,pol1);
// console.log("pol2 = " ,pol2);
