"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var package_1 = require("./package");
var fs = require('fs');
var inputString = fs.readFileSync("input.txt", "utf8");
var ecb = new package_1.ECB();
var encrypted = ecb.Encrypt(Buffer.from(inputString));
var ecb_res = ecb.Decrypt(encrypted).toString().split('\0').join('');
console.log("ECB testing... ", ecb_res === inputString, ecb_res.length, inputString.length);
var cbc = new package_1.CBC();
var cbc_enc = cbc.Encrypt(Buffer.from(inputString));
var cbc_res = cbc.Decrypt(cbc_enc).toString();
console.log("CBC testing... ", cbc_res === inputString, cbc_res.length, inputString.length);
var cfb = new package_1.CFB();
var cfb_enc = cfb.Encrypt(Buffer.from(inputString));
var cfb_res = cfb.Decrypt(cfb_enc).toString();
console.log("CFB testing... ", cfb_res === inputString, cfb_res.length, inputString.length);
var ctr = new package_1.CTR();
var ctr_enc = ctr.Encrypt(Buffer.from(inputString));
var ctr_res = ctr.Decrypt(ctr_enc).toString();
console.log("CTR testing... ", ctr_res === inputString, ctr_res.length, inputString.length);
var ofb = new package_1.OFB();
var ofb_enc = ofb.Encrypt(Buffer.from(inputString));
var ofb_res = ofb.Decrypt(ofb_enc).toString();
console.log("OFB testing... ", ofb_res === inputString, ofb_res.length, inputString.length);
var kuz = new package_1.Kuznec();
var block = Buffer.from('plainTextBlock12');
var encrypted_block = kuz.Encryption(block);
var decrypted_block = kuz.Decryption(encrypted_block);
console.log(decrypted_block.toString('utf-8')); //// plainTextBlock12
//# sourceMappingURL=sample.js.map